### ISSUE TITLE
Base Features

### ISSUE THREAD

**Issue by ibrahimsuzer** [ibrahimsuzer/chant#14]
## CLI

- [x] Config Files
  - [x] Add / Remove / List #13 
  - [ ] Update Versions
  - [ ] Move
- [ ] Versions
  - [ ] Update
  - [ ] List
  - [ ] Checkout
  - [ ] Diff
- [ ] Snippets
  - [ ] Add / Remove / List
  - [ ] Edit
  - [ ] List
  - [ ] Apply / Restore to Config
